from enum import Enum


class PipelineStep(str, Enum):
    RECEIVED = "RECEIVED"
    READING_POLICY = "READING_POLICY"
    ORGANIZING_POLICY = "ORGANIZING_POLICY"
    SAVING = "SAVING"
    READING_CLAIM = "READING_CLAIM"
    REVIEWING_CLAIM = "REVIEWING_CLAIM"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
